[package]
name = "baby_aggregation_program"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bincode = { workspace = true }
sp1-zkvm = { workspace = true, features = ["verify"] }
zk-light-client-core = { workspace = true }
