[package]
name = "baby_membership_program"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sp1-zkvm = { workspace = true }
zk-light-client-core = { workspace = true }
